# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fatura.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1127, 562)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(False)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setEnabled(False)
        self.table.setGeometry(QtCore.QRect(344, 221, 770, 300))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.table.setFont(font)
        self.table.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.table.setMouseTracking(False)
        self.table.setTabletTracking(False)
        self.table.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.table.setAutoFillBackground(False)
        self.table.setLineWidth(4)
        self.table.setMidLineWidth(5)
        self.table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table.setTabKeyNavigation(True)
        self.table.setProperty("showDropIndicator", True)
        self.table.setDragDropOverwriteMode(False)
        self.table.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table.setShowGrid(True)
        self.table.setGridStyle(QtCore.Qt.SolidLine)
        self.table.setWordWrap(True)
        self.table.setCornerButtonEnabled(False)
        self.table.setRowCount(13)
        self.table.setColumnCount(9)
        self.table.setObjectName("table")
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 206))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 206))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.table.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 206))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.table.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 206))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.table.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(104, 25, 33))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(44, 175, 52))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.table.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(104, 25, 33))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.table.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(44, 175, 52))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.table.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(104, 25, 33))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.table.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(44, 175, 52))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.table.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(104, 25, 33))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.table.setItem(1, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(44, 175, 52))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.table.setItem(1, 8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table.setItem(12, 0, item)
        self.table.horizontalHeader().setVisible(False)
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.horizontalHeader().setDefaultSectionSize(84)
        self.table.horizontalHeader().setMinimumSectionSize(39)
        self.table.verticalHeader().setVisible(False)
        self.table.verticalHeader().setCascadingSectionResizes(False)
        self.table.verticalHeader().setDefaultSectionSize(23)
        self.table.verticalHeader().setHighlightSections(True)
        self.table.verticalHeader().setMinimumSectionSize(18)
        self.table.verticalHeader().setSortIndicatorShown(False)
        self.table.verticalHeader().setStretchLastSection(False)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(15, 10, 1099, 195))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(104, 25, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(104, 25, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.groupBox.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.group_donem = QtWidgets.QGroupBox(self.groupBox)
        self.group_donem.setGeometry(QtCore.QRect(382, 22, 158, 158))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.group_donem.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.group_donem.setFont(font)
        self.group_donem.setTitle("")
        self.group_donem.setObjectName("group_donem")
        self.combo_yil = QtWidgets.QComboBox(self.group_donem)
        self.combo_yil.setGeometry(QtCore.QRect(64, 16, 84, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.combo_yil.setFont(font)
        self.combo_yil.setAutoFillBackground(False)
        self.combo_yil.setEditable(False)
        self.combo_yil.setObjectName("combo_yil")
        self.combo_yil.addItem("")
        self.combo_yil.addItem("")
        self.combo_yil.addItem("")
        self.combo_yil.addItem("")
        self.combo_yil.addItem("")
        self.label_2 = QtWidgets.QLabel(self.group_donem)
        self.label_2.setGeometry(QtCore.QRect(10, 16, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.combo_tes = QtWidgets.QComboBox(self.group_donem)
        self.combo_tes.setGeometry(QtCore.QRect(64, 121, 84, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.combo_tes.setFont(font)
        self.combo_tes.setAutoFillBackground(False)
        self.combo_tes.setEditable(False)
        self.combo_tes.setObjectName("combo_tes")
        self.combo_tes.addItem("")
        self.combo_tes.addItem("")
        self.combo_tes.addItem("")
        self.combo_tes.addItem("")
        self.combo_tes.addItem("")
        self.combo_seb = QtWidgets.QComboBox(self.group_donem)
        self.combo_seb.setGeometry(QtCore.QRect(64, 86, 84, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.combo_seb.setFont(font)
        self.combo_seb.setObjectName("combo_seb")
        self.combo_seb.addItem("")
        self.combo_seb.addItem("")
        self.label_4 = QtWidgets.QLabel(self.group_donem)
        self.label_4.setGeometry(QtCore.QRect(10, 121, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.group_donem)
        self.label.setGeometry(QtCore.QRect(10, 88, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.combo_ay = QtWidgets.QComboBox(self.group_donem)
        self.combo_ay.setGeometry(QtCore.QRect(64, 51, 84, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.combo_ay.setFont(font)
        self.combo_ay.setAutoFillBackground(False)
        self.combo_ay.setEditable(False)
        self.combo_ay.setObjectName("combo_ay")
        self.combo_ay.addItem("")
        self.combo_ay.addItem("")
        self.combo_ay.addItem("")
        self.combo_ay.addItem("")
        self.combo_ay.addItem("")
        self.combo_ay.addItem("")
        self.combo_ay.addItem("")
        self.combo_ay.addItem("")
        self.combo_ay.addItem("")
        self.combo_ay.addItem("")
        self.combo_ay.addItem("")
        self.combo_ay.addItem("")
        self.label_12 = QtWidgets.QLabel(self.group_donem)
        self.label_12.setGeometry(QtCore.QRect(10, 51, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.group_aktif = QtWidgets.QGroupBox(self.groupBox)
        self.group_aktif.setGeometry(QtCore.QRect(550, 16, 176, 164))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.group_aktif.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.group_aktif.setFont(font)
        self.group_aktif.setObjectName("group_aktif")
        self.label_3 = QtWidgets.QLabel(self.group_aktif)
        self.label_3.setGeometry(QtCore.QRect(30, 23, 91, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_15 = QtWidgets.QLabel(self.group_aktif)
        self.label_15.setGeometry(QtCore.QRect(30, 57, 91, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_15.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.group_aktif)
        self.label_17.setGeometry(QtCore.QRect(30, 91, 91, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_17.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.input_gunduz = QtWidgets.QLineEdit(self.group_aktif)
        self.input_gunduz.setGeometry(QtCore.QRect(120, 26, 46, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.input_gunduz.setFont(font)
        self.input_gunduz.setAlignment(QtCore.Qt.AlignCenter)
        self.input_gunduz.setObjectName("input_gunduz")
        self.input_puant = QtWidgets.QLineEdit(self.group_aktif)
        self.input_puant.setGeometry(QtCore.QRect(120, 60, 46, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.input_puant.setFont(font)
        self.input_puant.setAlignment(QtCore.Qt.AlignCenter)
        self.input_puant.setObjectName("input_puant")
        self.input_gece = QtWidgets.QLineEdit(self.group_aktif)
        self.input_gece.setGeometry(QtCore.QRect(120, 94, 46, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.input_gece.setFont(font)
        self.input_gece.setText("")
        self.input_gece.setAlignment(QtCore.Qt.AlignCenter)
        self.input_gece.setObjectName("input_gece")
        self.input_toplam = QtWidgets.QLineEdit(self.group_aktif)
        self.input_toplam.setEnabled(False)
        self.input_toplam.setGeometry(QtCore.QRect(120, 128, 46, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.input_toplam.setFont(font)
        self.input_toplam.setText("")
        self.input_toplam.setAlignment(QtCore.Qt.AlignCenter)
        self.input_toplam.setObjectName("input_toplam")
        self.label_18 = QtWidgets.QLabel(self.group_aktif)
        self.label_18.setEnabled(False)
        self.label_18.setGeometry(QtCore.QRect(30, 125, 91, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_18.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.radio_uclu = QtWidgets.QRadioButton(self.group_aktif)
        self.radio_uclu.setGeometry(QtCore.QRect(10, 60, 21, 17))
        self.radio_uclu.setText("")
        self.radio_uclu.setChecked(True)
        self.radio_uclu.setObjectName("radio_uclu")
        self.radio_tek = QtWidgets.QRadioButton(self.group_aktif)
        self.radio_tek.setGeometry(QtCore.QRect(10, 128, 21, 17))
        self.radio_tek.setText("")
        self.radio_tek.setObjectName("radio_tek")
        self.group_reak = QtWidgets.QGroupBox(self.groupBox)
        self.group_reak.setGeometry(QtCore.QRect(736, 16, 157, 164))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.group_reak.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.group_reak.setFont(font)
        self.group_reak.setObjectName("group_reak")
        self.label_5 = QtWidgets.QLabel(self.group_reak)
        self.label_5.setGeometry(QtCore.QRect(10, 47, 101, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_5.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_21 = QtWidgets.QLabel(self.group_reak)
        self.label_21.setGeometry(QtCore.QRect(10, 98, 101, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_21.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.input_kapas = QtWidgets.QLineEdit(self.group_reak)
        self.input_kapas.setGeometry(QtCore.QRect(106, 50, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.input_kapas.setFont(font)
        self.input_kapas.setAlignment(QtCore.Qt.AlignCenter)
        self.input_kapas.setObjectName("input_kapas")
        self.input_end = QtWidgets.QLineEdit(self.group_reak)
        self.input_end.setGeometry(QtCore.QRect(106, 102, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.input_end.setFont(font)
        self.input_end.setAlignment(QtCore.Qt.AlignCenter)
        self.input_end.setObjectName("input_end")
        self.group_cift = QtWidgets.QGroupBox(self.groupBox)
        self.group_cift.setGeometry(QtCore.QRect(903, 16, 186, 164))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.group_cift.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.group_cift.setFont(font)
        self.group_cift.setObjectName("group_cift")
        self.label_6 = QtWidgets.QLabel(self.group_cift)
        self.label_6.setGeometry(QtCore.QRect(10, 47, 131, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_6.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_22 = QtWidgets.QLabel(self.group_cift)
        self.label_22.setGeometry(QtCore.QRect(10, 98, 131, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_22.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.input_anma = QtWidgets.QLineEdit(self.group_cift)
        self.input_anma.setGeometry(QtCore.QRect(135, 50, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.input_anma.setFont(font)
        self.input_anma.setAlignment(QtCore.Qt.AlignCenter)
        self.input_anma.setObjectName("input_anma")
        self.input_sgucu = QtWidgets.QLineEdit(self.group_cift)
        self.input_sgucu.setGeometry(QtCore.QRect(135, 102, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.input_sgucu.setFont(font)
        self.input_sgucu.setAlignment(QtCore.Qt.AlignCenter)
        self.input_sgucu.setObjectName("input_sgucu")
        self.group_ted = QtWidgets.QGroupBox(self.groupBox)
        self.group_ted.setGeometry(QtCore.QRect(10, 16, 362, 164))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.group_ted.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.group_ted.setFont(font)
        self.group_ted.setObjectName("group_ted")
        self.radio_ulus = QtWidgets.QRadioButton(self.group_ted)
        self.radio_ulus.setGeometry(QtCore.QRect(5, 15, 61, 17))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(59, 118, 87))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(59, 118, 87))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.radio_ulus.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radio_ulus.setFont(font)
        self.radio_ulus.setChecked(True)
        self.radio_ulus.setObjectName("radio_ulus")
        self.radio_ikili = QtWidgets.QRadioButton(self.group_ted)
        self.radio_ikili.setGeometry(QtCore.QRect(89, 15, 91, 17))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(59, 118, 87))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(59, 118, 87))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.radio_ikili.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radio_ikili.setFont(font)
        self.radio_ikili.setObjectName("radio_ikili")
        self.radio_osb = QtWidgets.QRadioButton(self.group_ted)
        self.radio_osb.setGeometry(QtCore.QRect(264, 15, 41, 17))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(59, 118, 87))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(59, 118, 87))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.radio_osb.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radio_osb.setFont(font)
        self.radio_osb.setObjectName("radio_osb")
        self.line_2 = QtWidgets.QFrame(self.group_ted)
        self.line_2.setGeometry(QtCore.QRect(197, 6, 20, 157))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_7 = QtWidgets.QLabel(self.group_ted)
        self.label_7.setEnabled(False)
        self.label_7.setGeometry(QtCore.QRect(70, 48, 91, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_7.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.input_ikili = QtWidgets.QLineEdit(self.group_ted)
        self.input_ikili.setEnabled(False)
        self.input_ikili.setGeometry(QtCore.QRect(161, 48, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.input_ikili.setFont(font)
        self.input_ikili.setText("")
        self.input_ikili.setAlignment(QtCore.Qt.AlignCenter)
        self.input_ikili.setObjectName("input_ikili")
        self.input_osb_akt = QtWidgets.QLineEdit(self.group_ted)
        self.input_osb_akt.setEnabled(False)
        self.input_osb_akt.setGeometry(QtCore.QRect(316, 37, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.input_osb_akt.setFont(font)
        self.input_osb_akt.setText("")
        self.input_osb_akt.setAlignment(QtCore.Qt.AlignCenter)
        self.input_osb_akt.setObjectName("input_osb_akt")
        self.label_8 = QtWidgets.QLabel(self.group_ted)
        self.label_8.setEnabled(False)
        self.label_8.setGeometry(QtCore.QRect(212, 37, 101, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_8.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.input_osb_dag = QtWidgets.QLineEdit(self.group_ted)
        self.input_osb_dag.setEnabled(True)
        self.input_osb_dag.setGeometry(QtCore.QRect(316, 79, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.input_osb_dag.setFont(font)
        self.input_osb_dag.setText("")
        self.input_osb_dag.setAlignment(QtCore.Qt.AlignCenter)
        self.input_osb_dag.setObjectName("input_osb_dag")
        self.label_9 = QtWidgets.QLabel(self.group_ted)
        self.label_9.setGeometry(QtCore.QRect(212, 79, 101, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_9.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.check_ikili = QtWidgets.QCheckBox(self.group_ted)
        self.check_ikili.setGeometry(QtCore.QRect(102, 80, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.check_ikili.setFont(font)
        self.check_ikili.setChecked(True)
        self.check_ikili.setObjectName("check_ikili")
        self.check_osb = QtWidgets.QCheckBox(self.group_ted)
        self.check_osb.setGeometry(QtCore.QRect(247, 100, 76, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.check_osb.setFont(font)
        self.check_osb.setObjectName("check_osb")
        self.label_11 = QtWidgets.QLabel(self.group_ted)
        self.label_11.setGeometry(QtCore.QRect(212, 143, 111, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_11.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(self.group_ted)
        self.label_10.setGeometry(QtCore.QRect(212, 122, 111, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_10.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.input_osb_guc = QtWidgets.QLineEdit(self.group_ted)
        self.input_osb_guc.setEnabled(True)
        self.input_osb_guc.setGeometry(QtCore.QRect(316, 122, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.input_osb_guc.setFont(font)
        self.input_osb_guc.setText("")
        self.input_osb_guc.setAlignment(QtCore.Qt.AlignCenter)
        self.input_osb_guc.setObjectName("input_osb_guc")
        self.input_osb_guca = QtWidgets.QLineEdit(self.group_ted)
        self.input_osb_guca.setEnabled(True)
        self.input_osb_guca.setGeometry(QtCore.QRect(316, 144, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.input_osb_guca.setFont(font)
        self.input_osb_guca.setText("")
        self.input_osb_guca.setAlignment(QtCore.Qt.AlignCenter)
        self.input_osb_guca.setObjectName("input_osb_guca")
        self.line_3 = QtWidgets.QFrame(self.group_ted)
        self.line_3.setGeometry(QtCore.QRect(55, 6, 20, 157))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.input_ikili_2 = QtWidgets.QLineEdit(self.group_ted)
        self.input_ikili_2.setEnabled(True)
        self.input_ikili_2.setGeometry(QtCore.QRect(161, 110, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.input_ikili_2.setFont(font)
        self.input_ikili_2.setText("")
        self.input_ikili_2.setAlignment(QtCore.Qt.AlignCenter)
        self.input_ikili_2.setObjectName("input_ikili_2")
        self.label_13 = QtWidgets.QLabel(self.group_ted)
        self.label_13.setEnabled(True)
        self.label_13.setGeometry(QtCore.QRect(70, 110, 91, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_13.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.input_osb_akt_2 = QtWidgets.QLineEdit(self.group_ted)
        self.input_osb_akt_2.setEnabled(True)
        self.input_osb_akt_2.setGeometry(QtCore.QRect(316, 58, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.input_osb_akt_2.setFont(font)
        self.input_osb_akt_2.setText("")
        self.input_osb_akt_2.setAlignment(QtCore.Qt.AlignCenter)
        self.input_osb_akt_2.setObjectName("input_osb_akt_2")
        self.check_osb_ek = QtWidgets.QCheckBox(self.group_ted)
        self.check_osb_ek.setEnabled(True)
        self.check_osb_ek.setGeometry(QtCore.QRect(212, 57, 16, 17))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.check_osb_ek.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.check_osb_ek.setFont(font)
        self.check_osb_ek.setText("")
        self.check_osb_ek.setChecked(True)
        self.check_osb_ek.setObjectName("check_osb_ek")
        self.label_14 = QtWidgets.QLabel(self.group_ted)
        self.label_14.setEnabled(True)
        self.label_14.setGeometry(QtCore.QRect(230, 57, 81, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 136, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_14.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(15, 214, 311, 308))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(104, 25, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(104, 25, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.groupBox_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(10, 50, 171, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(58, 111, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 111, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_16.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(10, 80, 171, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(44, 175, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 175, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_23.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(10, 110, 171, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(44, 175, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 175, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_24.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(10, 140, 171, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(44, 175, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 175, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_25.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.input_ges = QtWidgets.QLineEdit(self.groupBox_3)
        self.input_ges.setEnabled(True)
        self.input_ges.setGeometry(QtCore.QRect(180, 53, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.input_ges.setFont(font)
        self.input_ges.setText("")
        self.input_ges.setAlignment(QtCore.Qt.AlignCenter)
        self.input_ges.setObjectName("input_ges")
        self.input_ges_gunduz = QtWidgets.QLineEdit(self.groupBox_3)
        self.input_ges_gunduz.setEnabled(True)
        self.input_ges_gunduz.setGeometry(QtCore.QRect(180, 83, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.input_ges_gunduz.setFont(font)
        self.input_ges_gunduz.setText("")
        self.input_ges_gunduz.setAlignment(QtCore.Qt.AlignCenter)
        self.input_ges_gunduz.setObjectName("input_ges_gunduz")
        self.input_ges_puant = QtWidgets.QLineEdit(self.groupBox_3)
        self.input_ges_puant.setEnabled(True)
        self.input_ges_puant.setGeometry(QtCore.QRect(180, 113, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.input_ges_puant.setFont(font)
        self.input_ges_puant.setText("")
        self.input_ges_puant.setAlignment(QtCore.Qt.AlignCenter)
        self.input_ges_puant.setObjectName("input_ges_puant")
        self.input_ges_gece = QtWidgets.QLineEdit(self.groupBox_3)
        self.input_ges_gece.setEnabled(False)
        self.input_ges_gece.setGeometry(QtCore.QRect(180, 143, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.input_ges_gece.setFont(font)
        self.input_ges_gece.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_ges_gece.setAlignment(QtCore.Qt.AlignCenter)
        self.input_ges_gece.setObjectName("input_ges_gece")
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(10, 190, 251, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(116, 25, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 25, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_26.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.input_ges_aylik = QtWidgets.QLineEdit(self.groupBox_3)
        self.input_ges_aylik.setEnabled(False)
        self.input_ges_aylik.setGeometry(QtCore.QRect(240, 190, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.input_ges_aylik.setFont(font)
        self.input_ges_aylik.setAlignment(QtCore.Qt.AlignCenter)
        self.input_ges_aylik.setObjectName("input_ges_aylik")
        self.input_ges_mali = QtWidgets.QLineEdit(self.groupBox_3)
        self.input_ges_mali.setEnabled(False)
        self.input_ges_mali.setGeometry(QtCore.QRect(240, 270, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.input_ges_mali.setFont(font)
        self.input_ges_mali.setAlignment(QtCore.Qt.AlignCenter)
        self.input_ges_mali.setObjectName("input_ges_mali")
        self.label_27 = QtWidgets.QLabel(self.groupBox_3)
        self.label_27.setGeometry(QtCore.QRect(10, 270, 241, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(116, 25, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 25, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_27.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_3)
        self.label_28.setGeometry(QtCore.QRect(10, 230, 251, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(116, 25, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 25, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_28.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.input_ges_alan = QtWidgets.QLineEdit(self.groupBox_3)
        self.input_ges_alan.setEnabled(False)
        self.input_ges_alan.setGeometry(QtCore.QRect(240, 230, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.input_ges_alan.setFont(font)
        self.input_ges_alan.setAlignment(QtCore.Qt.AlignCenter)
        self.input_ges_alan.setObjectName("input_ges_alan")
        self.check_ges = QtWidgets.QCheckBox(self.groupBox_3)
        self.check_ges.setEnabled(True)
        self.check_ges.setGeometry(QtCore.QRect(120, 20, 81, 17))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.check_ges.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.check_ges.setFont(font)
        self.check_ges.setChecked(False)
        self.check_ges.setTristate(False)
        self.check_ges.setObjectName("check_ges")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1127, 21))
        self.menuBar.setObjectName("menuBar")
        self.fileMenu = QtWidgets.QMenu(self.menuBar)
        self.fileMenu.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.fileMenu.setObjectName("fileMenu")
        MainWindow.setMenuBar(self.menuBar)
        self.actionKaydet = QtWidgets.QAction(MainWindow)
        self.actionKaydet.setObjectName("actionKaydet")
        self.actionA = QtWidgets.QAction(MainWindow)
        self.actionA.setWhatsThis("")
        self.actionA.setObjectName("actionA")
        self.actionFarkli = QtWidgets.QAction(MainWindow)
        self.actionFarkli.setObjectName("actionFarkli")
        self.fileMenu.addAction(self.actionA)
        self.fileMenu.addAction(self.actionKaydet)
        self.fileMenu.addAction(self.actionFarkli)
        self.menuBar.addAction(self.fileMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.radio_ulus, self.combo_yil)
        MainWindow.setTabOrder(self.combo_yil, self.combo_seb)
        MainWindow.setTabOrder(self.combo_seb, self.combo_tes)
        MainWindow.setTabOrder(self.combo_tes, self.input_gunduz)
        MainWindow.setTabOrder(self.input_gunduz, self.input_puant)
        MainWindow.setTabOrder(self.input_puant, self.input_gece)
        MainWindow.setTabOrder(self.input_gece, self.input_kapas)
        MainWindow.setTabOrder(self.input_kapas, self.input_end)
        MainWindow.setTabOrder(self.input_end, self.input_anma)
        MainWindow.setTabOrder(self.input_anma, self.input_sgucu)
        MainWindow.setTabOrder(self.input_sgucu, self.input_ges)
        MainWindow.setTabOrder(self.input_ges, self.input_ges_gunduz)
        MainWindow.setTabOrder(self.input_ges_gunduz, self.input_ges_puant)
        MainWindow.setTabOrder(self.input_ges_puant, self.input_ikili)
        MainWindow.setTabOrder(self.input_ikili, self.input_osb_akt)
        MainWindow.setTabOrder(self.input_osb_akt, self.input_osb_dag)
        MainWindow.setTabOrder(self.input_osb_dag, self.input_osb_guc)
        MainWindow.setTabOrder(self.input_osb_guc, self.input_osb_guca)
        MainWindow.setTabOrder(self.input_osb_guca, self.check_ges)
        MainWindow.setTabOrder(self.check_ges, self.radio_ikili)
        MainWindow.setTabOrder(self.radio_ikili, self.radio_osb)
        MainWindow.setTabOrder(self.radio_osb, self.check_osb)
        MainWindow.setTabOrder(self.check_osb, self.input_ges_aylik)
        MainWindow.setTabOrder(self.input_ges_aylik, self.table)
        MainWindow.setTabOrder(self.table, self.input_ges_gece)
        MainWindow.setTabOrder(self.input_ges_gece, self.input_ges_alan)
        MainWindow.setTabOrder(self.input_ges_alan, self.input_ges_mali)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "electraVis GES Fizibilite Programı"))
        self.table.setSortingEnabled(False)
        item = self.table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Aktif Tüketim"))
        item = self.table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Dağıtım Bedeli"))
        item = self.table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Güç Bedeli"))
        item = self.table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Güç Aşım Bedeli"))
        item = self.table.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Reaktif Ceza Bedeli"))
        item = self.table.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Enerji Fonu"))
        item = self.table.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "TRT Payı"))
        item = self.table.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "Belediye Vergisi"))
        item = self.table.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "KDV Matrahı"))
        item = self.table.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "KDV"))
        item = self.table.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "Toplam"))
        __sortingEnabled = self.table.isSortingEnabled()
        self.table.setSortingEnabled(False)
        item = self.table.item(0, 1)
        item.setText(_translate("MainWindow", "Tek Terimli Tek Zamanlı"))
        item = self.table.item(0, 3)
        item.setText(_translate("MainWindow", "Tek Terimli Üç Zamanlı"))
        item = self.table.item(0, 5)
        item.setText(_translate("MainWindow", "Çift Terimli Tek Zamanlı"))
        item = self.table.item(0, 7)
        item.setText(_translate("MainWindow", "Çift Terimli Üç Zamanlı"))
        item = self.table.item(1, 1)
        item.setText(_translate("MainWindow", "Normal"))
        item = self.table.item(1, 2)
        item.setText(_translate("MainWindow", "Çatı GES "))
        item = self.table.item(1, 3)
        item.setText(_translate("MainWindow", "Normal"))
        item = self.table.item(1, 4)
        item.setText(_translate("MainWindow", "Çatı GES"))
        item = self.table.item(1, 5)
        item.setText(_translate("MainWindow", "Normal"))
        item = self.table.item(1, 6)
        item.setText(_translate("MainWindow", "Çatı GES"))
        item = self.table.item(1, 7)
        item.setText(_translate("MainWindow", "Normal"))
        item = self.table.item(1, 8)
        item.setText(_translate("MainWindow", "Çatı GES"))
        item = self.table.item(2, 0)
        item.setText(_translate("MainWindow", "Aktif Tüketim"))
        item = self.table.item(3, 0)
        item.setText(_translate("MainWindow", "Dağıtım"))
        item = self.table.item(4, 0)
        item.setText(_translate("MainWindow", "Güç Bedeli"))
        item = self.table.item(5, 0)
        item.setText(_translate("MainWindow", "Güç Aşım Bedeli"))
        item = self.table.item(6, 0)
        item.setText(_translate("MainWindow", "Reaktif Ceza"))
        item = self.table.item(7, 0)
        item.setText(_translate("MainWindow", "Enerji Fonu"))
        item = self.table.item(8, 0)
        item.setText(_translate("MainWindow", "TRT Payı"))
        item = self.table.item(9, 0)
        item.setText(_translate("MainWindow", "Belediye Vergisi"))
        item = self.table.item(10, 0)
        item.setText(_translate("MainWindow", "KDV Matrahı"))
        item = self.table.item(11, 0)
        item.setText(_translate("MainWindow", "KDV"))
        item = self.table.item(12, 0)
        item.setText(_translate("MainWindow", "Toplam"))
        self.table.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("MainWindow", "Fatura Bilgileri"))
        self.combo_yil.setCurrentText(_translate("MainWindow", "2016"))
        self.combo_yil.setItemText(0, _translate("MainWindow", "2016"))
        self.combo_yil.setItemText(1, _translate("MainWindow", "2017"))
        self.combo_yil.setItemText(2, _translate("MainWindow", "2018"))
        self.combo_yil.setItemText(3, _translate("MainWindow", "2019"))
        self.combo_yil.setItemText(4, _translate("MainWindow", "2020"))
        self.label_2.setText(_translate("MainWindow", "Yıl          :"))
        self.combo_tes.setCurrentText(_translate("MainWindow", "Mesken"))
        self.combo_tes.setItemText(0, _translate("MainWindow", "Mesken"))
        self.combo_tes.setItemText(1, _translate("MainWindow", "Sanayi"))
        self.combo_tes.setItemText(2, _translate("MainWindow", "Ticarethane"))
        self.combo_tes.setItemText(3, _translate("MainWindow", "Tarımsal Sulama"))
        self.combo_tes.setItemText(4, _translate("MainWindow", "Aydınlatma"))
        self.combo_seb.setItemText(0, _translate("MainWindow", "Alçak Gerilim"))
        self.combo_seb.setItemText(1, _translate("MainWindow", "Orta Gerilim"))
        self.label_4.setText(_translate("MainWindow", "Tesis    :"))
        self.label.setText(_translate("MainWindow", "Şebeke:"))
        self.combo_ay.setCurrentText(_translate("MainWindow", "Ocak"))
        self.combo_ay.setItemText(0, _translate("MainWindow", "Ocak"))
        self.combo_ay.setItemText(1, _translate("MainWindow", "Şubat"))
        self.combo_ay.setItemText(2, _translate("MainWindow", "Mart"))
        self.combo_ay.setItemText(3, _translate("MainWindow", "Nisan"))
        self.combo_ay.setItemText(4, _translate("MainWindow", "Mayıs"))
        self.combo_ay.setItemText(5, _translate("MainWindow", "Haziran"))
        self.combo_ay.setItemText(6, _translate("MainWindow", "Temmuz"))
        self.combo_ay.setItemText(7, _translate("MainWindow", "Ağustos"))
        self.combo_ay.setItemText(8, _translate("MainWindow", "Eylül"))
        self.combo_ay.setItemText(9, _translate("MainWindow", "Ekim"))
        self.combo_ay.setItemText(10, _translate("MainWindow", "Kasım"))
        self.combo_ay.setItemText(11, _translate("MainWindow", "Aralık"))
        self.label_12.setText(_translate("MainWindow", "Ay         : "))
        self.group_aktif.setTitle(_translate("MainWindow", "Aktif Tüketim"))
        self.label_3.setText(_translate("MainWindow", "Gündüz (kWh):"))
        self.label_15.setText(_translate("MainWindow", "Puant (kWh)   :"))
        self.label_17.setText(_translate("MainWindow", "Gece (kWh)     :"))
        self.label_18.setText(_translate("MainWindow", "Toplam (kWh):"))
        self.group_reak.setTitle(_translate("MainWindow", "Reaktif Tüketim"))
        self.label_5.setText(_translate("MainWindow", "Kapasitif (kWh):"))
        self.label_21.setText(_translate("MainWindow", "Endüktif (kWh) :"))
        self.group_cift.setTitle(_translate("MainWindow", "Çift Terimli Tarife Bilgileri"))
        self.label_6.setText(_translate("MainWindow", "Anma Değeri (kW)    :"))
        self.label_22.setText(_translate("MainWindow", "Sözleşme Gücü (kW):"))
        self.group_ted.setTitle(_translate("MainWindow", "Tedarikçi"))
        self.radio_ulus.setText(_translate("MainWindow", "Ulusal"))
        self.radio_ikili.setText(_translate("MainWindow", "İkili Anlaşma"))
        self.radio_osb.setText(_translate("MainWindow", "OSB"))
        self.label_7.setText(_translate("MainWindow", "Aktif (₺/MWh):"))
        self.label_8.setText(_translate("MainWindow", "Aktif (₺/MWh)    :"))
        self.label_9.setText(_translate("MainWindow", "Dağıtım (₺/kWh):"))
        self.check_ikili.setText(_translate("MainWindow", "Ek Bedelle"))
        self.check_osb.setText(_translate("MainWindow", "Çift Terimli"))
        self.label_11.setText(_translate("MainWindow", "Güç Aşım (Kr/kW):"))
        self.label_10.setText(_translate("MainWindow", "Güç (Kr/kW)          :"))
        self.label_13.setText(_translate("MainWindow", "Ek (Binde)        :"))
        self.label_14.setText(_translate("MainWindow", "Ek (Binde)      :"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Çatı GES"))
        self.label_16.setText(_translate("MainWindow", "Kurulacak Güç (kW)               :"))
        self.label_23.setText(_translate("MainWindow", "Gündüz Üretim Yüzdesi (%):"))
        self.label_24.setText(_translate("MainWindow", "Puant Üretim Yüzdesi (%)   :"))
        self.label_25.setText(_translate("MainWindow", "Gece Üretim Yüzdesi (%)    :"))
        self.input_ges_gece.setText(_translate("MainWindow", "Oto"))
        self.label_26.setText(_translate("MainWindow", "Ortalama Aylık Üretim (kWh)           :"))
        self.input_ges_aylik.setText(_translate("MainWindow", "Oto"))
        self.input_ges_mali.setText(_translate("MainWindow", "Oto"))
        self.label_27.setText(_translate("MainWindow", "Ortalama Anahtar Teslim Maliyet ($):"))
        self.label_28.setText(_translate("MainWindow", "Ortalama Gerekli Alan (m²)              :"))
        self.input_ges_alan.setText(_translate("MainWindow", "Oto"))
        self.check_ges.setText(_translate("MainWindow", "Otomatik"))
        self.fileMenu.setTitle(_translate("MainWindow", "Dosya"))
        self.actionKaydet.setText(_translate("MainWindow", "Kaydet"))
        self.actionKaydet.setStatusTip(_translate("MainWindow", "Verileri kaydet"))
        self.actionKaydet.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionA.setText(_translate("MainWindow", "Aç"))
        self.actionA.setStatusTip(_translate("MainWindow", "Kaydedilmiş veriyi aç"))
        self.actionA.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionFarkli.setText(_translate("MainWindow", "Farklı Kaydet"))
        self.actionFarkli.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
